version: "3.8"
services:
  frontend:
    build:
      context: ../.
      dockerfile: docker/frontend/Dockerfile
    ports:
      - 3000:3000
    networks:
      - starskynet
networks:
  starskynet:
    external:
      name: starsky_network
