/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    UserResponse,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models';

/**
 * 
 */
export class EmployeeApi extends runtime.BaseAPI {

    /**
     * Returns the currently authenticated user\'s employees - manager only route.
     * Get the authenticated manager\'s employees
     */
    async getEmployeesRaw(): Promise<runtime.ApiResponse<Array<UserResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearerAuth", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/user/employees`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserResponseFromJSON));
    }

    /**
     * Returns the currently authenticated user\'s employees - manager only route.
     * Get the authenticated manager\'s employees
     */
    async getEmployees(): Promise<Array<UserResponse>> {
        const response = await this.getEmployeesRaw();
        return await response.value();
    }

}
