/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateScheduleRequest
 */
export interface CreateScheduleRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateScheduleRequest
     */
    scheduleName: string;
    /**
     * 
     * @type {number}
     * @memberof CreateScheduleRequest
     */
    scheduleStart: number;
    /**
     * 
     * @type {number}
     * @memberof CreateScheduleRequest
     */
    scheduleEnd: number;
    /**
     * 
     * @type {number}
     * @memberof CreateScheduleRequest
     */
    maxHoursPerEmployee: number;
    /**
     * 
     * @type {number}
     * @memberof CreateScheduleRequest
     */
    maxShiftsPerEmployee: number;
    /**
     * 
     * @type {number}
     * @memberof CreateScheduleRequest
     */
    maxHoursPerShift: number;
}

export function CreateScheduleRequestFromJSON(json: any): CreateScheduleRequest {
    return CreateScheduleRequestFromJSONTyped(json, false);
}

export function CreateScheduleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateScheduleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scheduleName': json['schedule_name'],
        'scheduleStart': json['schedule_start'],
        'scheduleEnd': json['schedule_end'],
        'maxHoursPerEmployee': json['max_hours_per_employee'],
        'maxShiftsPerEmployee': json['max_shifts_per_employee'],
        'maxHoursPerShift': json['max_hours_per_shift'],
    };
}

export function CreateScheduleRequestToJSON(value?: CreateScheduleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schedule_name': value.scheduleName,
        'schedule_start': value.scheduleStart,
        'schedule_end': value.scheduleEnd,
        'max_hours_per_employee': value.maxHoursPerEmployee,
        'max_shifts_per_employee': value.maxShiftsPerEmployee,
        'max_hours_per_shift': value.maxHoursPerShift,
    };
}


