/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEmployeeAvailabilityRequest
 */
export interface CreateEmployeeAvailabilityRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateEmployeeAvailabilityRequest
     */
    availabilityStart: number;
    /**
     * 
     * @type {number}
     * @memberof CreateEmployeeAvailabilityRequest
     */
    availabilityEnd: number;
    /**
     * 
     * @type {number}
     * @memberof CreateEmployeeAvailabilityRequest
     */
    maxHoursPerShift: number;
    /**
     * 
     * @type {number}
     * @memberof CreateEmployeeAvailabilityRequest
     */
    employeeId: number;
}

export function CreateEmployeeAvailabilityRequestFromJSON(json: any): CreateEmployeeAvailabilityRequest {
    return CreateEmployeeAvailabilityRequestFromJSONTyped(json, false);
}

export function CreateEmployeeAvailabilityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmployeeAvailabilityRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availabilityStart': json['availability_start'],
        'availabilityEnd': json['availability_end'],
        'maxHoursPerShift': json['max_hours_per_shift'],
        'employeeId': json['employee_id'],
    };
}

export function CreateEmployeeAvailabilityRequestToJSON(value?: CreateEmployeeAvailabilityRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availability_start': value.availabilityStart,
        'availability_end': value.availabilityEnd,
        'max_hours_per_shift': value.maxHoursPerShift,
        'employee_id': value.employeeId,
    };
}


