/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateInviteRequest
 */
export interface CreateInviteRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateInviteRequest
     */
    employeeName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInviteRequest
     */
    employeeEmail: string;
}

export function CreateInviteRequestFromJSON(json: any): CreateInviteRequest {
    return CreateInviteRequestFromJSONTyped(json, false);
}

export function CreateInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInviteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'employeeName': json['employee_name'],
        'employeeEmail': json['employee_email'],
    };
}

export function CreateInviteRequestToJSON(value?: CreateInviteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'employee_name': value.employeeName,
        'employee_email': value.employeeEmail,
    };
}


