/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmployeeAvailabilityResponse
 */
export interface EmployeeAvailabilityResponse {
    /**
     * 
     * @type {number}
     * @memberof EmployeeAvailabilityResponse
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeAvailabilityResponse
     */
    shiftStart?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeAvailabilityResponse
     */
    shiftEnd?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeAvailabilityResponse
     */
    maxHoursPerShift?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeAvailabilityResponse
     */
    employeeId: number;
}

export function EmployeeAvailabilityResponseFromJSON(json: any): EmployeeAvailabilityResponse {
    return EmployeeAvailabilityResponseFromJSONTyped(json, false);
}

export function EmployeeAvailabilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeAvailabilityResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'shiftStart': !exists(json, 'shift_start') ? undefined : json['shift_start'],
        'shiftEnd': !exists(json, 'shift_end') ? undefined : json['shift_end'],
        'maxHoursPerShift': !exists(json, 'max_hours_per_shift') ? undefined : json['max_hours_per_shift'],
        'employeeId': json['employee_id'],
    };
}

export function EmployeeAvailabilityResponseToJSON(value?: EmployeeAvailabilityResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'shift_start': value.shiftStart,
        'shift_end': value.shiftEnd,
        'max_hours_per_shift': value.maxHoursPerShift,
        'employee_id': value.employeeId,
    };
}


