/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteInvalidResponse
 */
export interface InviteInvalidResponse {
    /**
     * 
     * @type {string}
     * @memberof InviteInvalidResponse
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof InviteInvalidResponse
     */
    inviteToken?: string;
}

export function InviteInvalidResponseFromJSON(json: any): InviteInvalidResponse {
    return InviteInvalidResponseFromJSONTyped(json, false);
}

export function InviteInvalidResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteInvalidResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
        'inviteToken': !exists(json, 'invite_token') ? undefined : json['invite_token'],
    };
}

export function InviteInvalidResponseToJSON(value?: InviteInvalidResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
        'invite_token': value.inviteToken,
    };
}


