/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteResponse
 */
export interface InviteResponse {
    /**
     * 
     * @type {number}
     * @memberof InviteResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InviteResponse
     */
    employeeName: string;
    /**
     * 
     * @type {string}
     * @memberof InviteResponse
     */
    employeeEmail: string;
    /**
     * 
     * @type {boolean}
     * @memberof InviteResponse
     */
    hasRegistered: boolean;
    /**
     * 
     * @type {number}
     * @memberof InviteResponse
     */
    expiresOn: number;
    /**
     * 
     * @type {number}
     * @memberof InviteResponse
     */
    expiresIn: number;
}

export function InviteResponseFromJSON(json: any): InviteResponse {
    return InviteResponseFromJSONTyped(json, false);
}

export function InviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'employeeName': json['employee_name'],
        'employeeEmail': json['employee_email'],
        'hasRegistered': json['has_registered'],
        'expiresOn': json['expires_on'],
        'expiresIn': json['expires_in'],
    };
}

export function InviteResponseToJSON(value?: InviteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'employee_name': value.employeeName,
        'employee_email': value.employeeEmail,
        'has_registered': value.hasRegistered,
        'expires_on': value.expiresOn,
        'expires_in': value.expiresIn,
    };
}


