/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleResponse
 */
export interface ScheduleResponse {
    /**
     * 
     * @type {number}
     * @memberof ScheduleResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduleResponse
     */
    scheduleName?: string;
    /**
     * 
     * @type {number}
     * @memberof ScheduleResponse
     */
    scheduleStart?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleResponse
     */
    scheduleEnd?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleResponse
     */
    teamId?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleResponse
     */
    maxHoursPerEmployee?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleResponse
     */
    maxShiftsPerEmployee?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleResponse
     */
    maxHoursPerShift?: number;
}

export function ScheduleResponseFromJSON(json: any): ScheduleResponse {
    return ScheduleResponseFromJSONTyped(json, false);
}

export function ScheduleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'scheduleName': !exists(json, 'schedule_name') ? undefined : json['schedule_name'],
        'scheduleStart': !exists(json, 'schedule_start') ? undefined : json['schedule_start'],
        'scheduleEnd': !exists(json, 'schedule_end') ? undefined : json['schedule_end'],
        'teamId': !exists(json, 'team_id') ? undefined : json['team_id'],
        'maxHoursPerEmployee': !exists(json, 'max_hours_per_employee') ? undefined : json['max_hours_per_employee'],
        'maxShiftsPerEmployee': !exists(json, 'max_shifts_per_employee') ? undefined : json['max_shifts_per_employee'],
        'maxHoursPerShift': !exists(json, 'max_hours_per_shift') ? undefined : json['max_hours_per_shift'],
    };
}

export function ScheduleResponseToJSON(value?: ScheduleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'schedule_name': value.scheduleName,
        'schedule_start': value.scheduleStart,
        'schedule_end': value.scheduleEnd,
        'team_id': value.teamId,
        'max_hours_per_employee': value.maxHoursPerEmployee,
        'max_shifts_per_employee': value.maxShiftsPerEmployee,
        'max_hours_per_shift': value.maxHoursPerShift,
    };
}


