/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamResponse
 */
export interface TeamResponse {
    /**
     * 
     * @type {number}
     * @memberof TeamResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    ownerName?: string;
}

export function TeamResponseFromJSON(json: any): TeamResponse {
    return TeamResponseFromJSONTyped(json, false);
}

export function TeamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'ownerName': !exists(json, 'owner_name') ? undefined : json['owner_name'],
    };
}

export function TeamResponseToJSON(value?: TeamResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'owner_name': value.ownerName,
    };
}


