/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEmployeeRequest
 */
export interface UpdateEmployeeRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeRequest
     */
    jobTitle?: string;
}

export function UpdateEmployeeRequestFromJSON(json: any): UpdateEmployeeRequest {
    return UpdateEmployeeRequestFromJSONTyped(json, false);
}

export function UpdateEmployeeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmployeeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'jobTitle': !exists(json, 'job_title') ? undefined : json['job_title'],
    };
}

export function UpdateEmployeeRequestToJSON(value?: UpdateEmployeeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'job_title': value.jobTitle,
    };
}


