/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateScheduleShiftRequest
 */
export interface UpdateScheduleShiftRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateScheduleShiftRequest
     */
    shiftStart?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateScheduleShiftRequest
     */
    shiftEnd?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateScheduleShiftRequest
     */
    numberOfRequiredEmployees?: number;
}

export function UpdateScheduleShiftRequestFromJSON(json: any): UpdateScheduleShiftRequest {
    return UpdateScheduleShiftRequestFromJSONTyped(json, false);
}

export function UpdateScheduleShiftRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateScheduleShiftRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shiftStart': !exists(json, 'shift_start') ? undefined : json['shift_start'],
        'shiftEnd': !exists(json, 'shift_end') ? undefined : json['shift_end'],
        'numberOfRequiredEmployees': !exists(json, 'number_of_required_employees') ? undefined : json['number_of_required_employees'],
    };
}

export function UpdateScheduleShiftRequestToJSON(value?: UpdateScheduleShiftRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shift_start': value.shiftStart,
        'shift_end': value.shiftEnd,
        'number_of_required_employees': value.numberOfRequiredEmployees,
    };
}


