/* tslint:disable */
/* eslint-disable */
/**
 * Starsky API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEmployeeAssignmentRequest
 */
export interface UpdateEmployeeAssignmentRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateEmployeeAssignmentRequest
     */
    assignmentStart?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateEmployeeAssignmentRequest
     */
    assignmentEnd?: number;
}

export function UpdateEmployeeAssignmentRequestFromJSON(json: any): UpdateEmployeeAssignmentRequest {
    return UpdateEmployeeAssignmentRequestFromJSONTyped(json, false);
}

export function UpdateEmployeeAssignmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmployeeAssignmentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assignmentStart': !exists(json, 'assignment_start') ? undefined : json['assignment_start'],
        'assignmentEnd': !exists(json, 'assignment_end') ? undefined : json['assignment_end'],
    };
}

export function UpdateEmployeeAssignmentRequestToJSON(value?: UpdateEmployeeAssignmentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assignment_start': value.assignmentStart,
        'assignment_end': value.assignmentEnd,
    };
}


